### PR TITLE
[GAL-307] [GAL-306] Popover Improvement

### PR DESCRIPTION
**Pull request by jakzaizzat**
## Small Updates

**Hide the follow button if its logged in user card**

CleanShot 2022-07-27 at 23 14 49

**Removed the hidden collection from total number**

CleanShot 2022-07-28 at 09 40 27

### CODE REVIEW

**Comment by Robinnnnn** [comment]
this is awesome! is it ready for review?!

**Comment by jakzaizzat** [comment]
@Robinnnnn Yes! Just finalized the total collection and now is ready

**Review by Robinnnnn — APPROVED** [review]
sweeettt

**Comment by kaitoo1** [comment]
awesome! thanks @jakzaizzat !

**Pull request merged**
