### PR TITLE
[GAL-329] Fix broken OG Image link

### PR DESCRIPTION
**Pull request by jakzaizzat**
**Changes**
1. Set initial height to image since some SVG dont have it
2. Trim the nft description on single nft preview link

**Before/After - NFT Description**

CleanShot 2022-08-11 at 13 04 15
CleanShot 2022-08-11 at 13 02 39

**Before/After - Single NFT (SVG)**

CleanShot 2022-08-11 at 13 04 43
CleanShot 2022-08-11 at 13 05 07

**Before/After - Collection with NFT (SVG)**

CleanShot 2022-08-11 at 13 05 32
CleanShot 2022-08-11 at 13 05 46

### CODE REVIEW

**Comment by Robinnnnn** [comment]
follow-up: looks like i broke it 😓 

using `width: 100%` only stretched it out lol

image

confusing though because it looks fine on the preview URL 🤔 
 https://gallery.so/opengraph/collection/27JCqjzgKo6zicp0RZ5l2rhCuZ7

**Comment by jakzaizzat** [comment]
Yo @Robinnnnn . Thats weird, I test the `main` branch on og image locally seems fine 🤔

**Comment by jakzaizzat** [comment]
Seems like 2/3 cases still need to fix. 

CleanShot 2022-08-12 at 08 14 39
CleanShot 2022-08-12 at 08 14 21

**Comment by Robinnnnn** [comment]
thank you @jakzaizzat !

**Review by Robinnnnn — APPROVED** [review]
🔥🔥🔥🔥

**Pull request merged**
