### PR TITLE
Upgrade moon to v1.21

### PR DESCRIPTION
**Pull request by milesj**
### Summary of Changes

Been a few releases, so updating! 

Changelog: https://github.com/moonrepo/moon/releases/tag/v1.21.0

cc: @Robinnnnn 

### Testing Steps

CI

### Checklist

Please make sure to review and check all of the following:

- [ ] I've tested the changes and all tests pass.
- [ ] (if web) I've tested the changes on various desktop screen sizes to ensure responsiveness.
- [ ] (if mobile) I've tested the changes on both light and dark modes.

### CODE REVIEW

**Review by Robinnnnn — COMMENTED** [review]
@milesj getting an unusual error when running a moon command
```
gallery git:(moon-v1.21) $ moon run web:dev

dyld[15839]: Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
  Referenced from: <C048742C-1815-39F0-9DBC-BA09803963B8> /Users/slothpotato/Cortana/gallery/node_modules/@moonrepo/cli/moon
  Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file)
```

**Comment by Robinnnnn** [comment]
seems like the moon binary itself doesn't get installed properly. tried going back and forth and get the error consistently, while reviving moon v1.18 works

image

**Comment by Robinnnnn** [comment]
https://www.loom.com/share/3da4dfbd7f8148188e48f674cf59a505?sid=e350d42e-d2ba-420c-9b2f-4e7139b82054

**Comment by milesj** [comment]
@Robinnnnn Is your mac x64 or arm64?

**Comment by Robinnnnn** [comment]
@milesj arm64 (M2)

no dice on `--log trace`

image

**Comment by milesj** [comment]
Interesting, in also on arm64 and it works. Let me dig further.

This was built with the new github macos-14 runners, so maybe it produced a different binary than before.

**Comment by milesj** [comment]
@Robinnnnn ok try again

**Review by Robinnnnn — APPROVED** [review]
works beautifully now @milesj !

**Comment by milesj** [comment]
Sweet

**Pull request merged**
